### ISSUE TITLE
Identify people not looking straight at the camera 

### ISSUE THREAD

**Issue by blanche** [utkuozbulak/facial-expression-recognition#10]
Maybe we need to filter them

**Comment by utkuozbulak** [comment]
No, algorithm  should be able to handle it, as in, we should not look at 28k images and filter people who are not looking straight at the camera

**Comment by blanche** [comment]
Sure but maybe we can improve the algorithm by weighting on how much they look into the camera or not. And its nice for evaluation i.e. "we were also able to detect X% of people not looking into the camera"

**Comment by blanche** [comment]
Also it's nice for evaluation

**Comment by blanche** [comment]
obsoleted by #12
