### ISSUE TITLE
Deadline: Feb 13 - Write project brief

### ISSUE THREAD

**Issue by utkuozbulak** [utkuozbulak/facial-expression-recognition#3]
edit LW: https://docs.google.com/document/d/1q_lt6z0KH4G2pkVJaCrMfTIUkYH31QRSpb9Ju4xm63E

**Comment by arahayrabedian** [comment]
~~can i move this to projects?~~

**Comment by arahayrabedian** [comment]
https://github.com/utkuozbulak/facial-expression-recognition/projects/1#card-1625051

**Comment by blanche** [comment]
hm, usually you add the issue on the project board?

**Comment by arahayrabedian** [comment]
i didn't find that!

**Comment by blanche** [comment]
isn't the deadline this Friday? because that would be the 10th
edit: no, it's week 3

**Comment by blanche** [comment]
https://docs.google.com/document/d/1q_lt6z0KH4G2pkVJaCrMfTIUkYH31QRSpb9Ju4xm63E

**Comment by blanche** [comment]
can someone have a look?

**Comment by arahayrabedian** [comment]
@blanche need the perms apparently

**Comment by utkuozbulak** [comment]
Looking as well
